### ISSUE TITLE
Não funciona com iPhone 4 com iOS 7.1.2 (11D257)

### ISSUE THREAD

**Issue by caiofbpa** [rafaelc0sta/MapsAllCountries#3]
Estou com um iPhone 4 temporário até eu pegar um mais recente, e lembrei de ter usado esse Tweak no meu finado iPhone 5 anos atrás. Tentei instalar no iPhone 4 mas o Maps insiste em me dar instruções e não o curva-a-curva.

Sou desenvolvedor e queria contribuir para consertar o Tweak para essa versão do iOS que é a final pro iPhone 4.

Tens dicas de como eu debugo o que está acontecendo de errado, para consertar e abrir uma PR aqui pra vocês?

**Comment by BrunoNFL** [comment]
Opa Caio!
Demorou mas vi seu problema.
O iPhone 4 não suporta navegação curva-a curva no Apple Maps, infelizmente. Tenho um iPhone 4 aqui e não funciona mesmo de forma alguma.
Abraço!

**Comment by caiofbpa** [comment]
Que pena Bruno!
